# Use postgres/example user/password credentials
version: '3.1'

volumes:
  postgres:

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smart_cocking
      PGDATA: /data/postgres
  #  volumes:
  #     - postgres:/data/postgres
    ports:
      - 5432:5432
    restart: unless-stopped

  web:
    container_name: web_container
    build: ./frontend
    ports:
      - 8081:3000
    depends_on:
      - postgres
    restart: unless-stopped

  backend:
    container_name: backend_container
    build: ./backend
    depends_on:
      - web
    ports:
      - 3001:3000
    links:
      - postgres:database
    restart: unless-stopped
    environment:
      POSTGRES_URL: 'database'
