# Use postgres/example user/password credentials
version: '3.1'
      
volumes:
  data:

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD: savePostgresPassword
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
#   myapp:
#     image: [YOUR-APP-IMAGE]
